FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
git \
cmake \
build-essential \
&& rm -rf /var/lib/apt/lists/* 


WORKDIR /app

RUN git clone https://github.com/DaveGamble/cJSON.git 

WORKDIR /app/cJSON

RUN mkdir build

WORKDIR /app/cJSON/build
RUN cmake .. && make

